controller:
  image:
    tag: "lts-jdk11"

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - docker-workflow
    - credentials-binding
    - blueocean

  serviceType: LoadBalancer
  servicePort: 8000

  admin:
    username: admin
    password: admin123

  ingress:
    enabled: false

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"

  persistence:
    enabled: true
    size: 8Gi
    storageClass: gp2

agent:
  enabled: true
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
