apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Abdu-khaled/Simple-GitOps-App.git'
    path: argo-cd
    targetRevision: main 
  desrtination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      sltfHeal: true
      prune: true
      