apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://abdu-khaled.github.io/Simple-GitOps-App/charts
    chart: httpd
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

